# Generated by Django 4.2.15 on 2026-09-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("profiles", "0002_migrate_membership_identity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_platform_admin",
        ),
    ]
