# Generated by Django 4.2.15 on 2026-09-13 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0004_membership_last_sync_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True,
                        help_text="Global identity key. Must be unique across all players.",
                        max_length=128,
                        region=None,
                        unique=True,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional. Clubs may override with their own display_name via ClubPlayer.",
                        max_length=255,
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="Verification state is independent from authentication. A player is not verified until an explicit verification step runs.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to an authenticated account. NULL means the player exists without an account.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClubPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Club-specific name override. Blank means the global full_name is used.",
                        max_length=255,
                    ),
                ),
                (
                    "player_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Club-internal jersey or member number.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_players",
                        to="clubs.club",
                    ),
                ),
                (
                    "player_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_players",
                        to="players.playerprofile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="playerprofile",
            index=models.Index(
                fields=["phone_number"], name="players_pla_phone_n_92fc44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerprofile",
            index=models.Index(fields=["user"], name="players_pla_user_id_0a96ec_idx"),
        ),
        migrations.AddIndex(
            model_name="clubplayer",
            index=models.Index(fields=["club"], name="players_clu_club_id_c0c27a_idx"),
        ),
        migrations.AddIndex(
            model_name="clubplayer",
            index=models.Index(
                fields=["player_profile"], name="players_clu_player__7bb11c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clubplayer",
            index=models.Index(
                fields=["club", "player_profile"], name="players_clu_club_id_d46971_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clubplayer",
            constraint=models.UniqueConstraint(
                fields=("club", "player_profile"), name="unique_club_player_profile"
            ),
        ),
    ]
