# Generated by Django 4.2.15 on 2026-09-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clubplayer",
            name="unique_club_player_profile",
        ),
        migrations.AddField(
            model_name="clubplayer",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Soft-delete marker. NULL means this is the current/active identity row for its (club, player_profile) pair. Set only by apps.players.services.supersede_club_player() when this row's identity information is replaced by a new ClubPlayer row. A deleted row is never physically removed and never resurrected — it remains permanently as the historical identity referenced by any Booking that was created while it was active.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="clubplayer",
            index=models.Index(
                fields=["deleted_at"], name="players_clu_deleted_0486bd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clubplayer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("club", "player_profile"),
                name="unique_active_club_player_profile",
            ),
        ),
    ]
