# Generated by Django 4.2.15 on 2026-09-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_club_player_soft_delete"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clubplayer",
            name="unique_active_club_player_profile",
        ),
        migrations.RemoveIndex(
            model_name="clubplayer",
            name="players_clu_deleted_0486bd_idx",
        ),
        migrations.RemoveField(
            model_name="clubplayer",
            name="deleted_at",
        ),
        migrations.AddField(
            model_name="clubplayer",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Recency marker, NOT a lifecycle/delete flag. Set at creation and bumped every time get_or_create_club_player() resolves this exact row again (i.e. this (display_name, player_number) is reused). Used only to pick a sensible default 'preferred' row for a (club, player_profile) pair when multiple historical rows exist — see get_preferred_club_player(). Never used to decide identity for an existing Booking; a Booking's club_player_id is fixed at creation time regardless of what becomes preferred afterwards.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="clubplayer",
            index=models.Index(
                fields=["last_used_at"], name="players_clu_last_us_162286_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clubplayer",
            constraint=models.UniqueConstraint(
                fields=("club", "player_profile", "display_name", "player_number"),
                name="unique_club_player_version",
            ),
        ),
    ]
