# Generated by Django 4.2.15 on 2026-09-13 21:39

import django.db.models.deletion
from django.db import migrations, models


def backfill_current_versions(apps, schema_editor):
    """
    For each (club, player_profile) chain existing rows by id and mark
    the newest as the current version. Safe when there is already only
    one row per pair (the usual case before content-based uniqueness).
    """
    ClubPlayer = apps.get_model("players", "ClubPlayer")
    grouped = {}
    for row in ClubPlayer.objects.all().order_by(
        "club_id", "player_profile_id", "id"
    ):
        grouped.setdefault((row.club_id, row.player_profile_id), []).append(row)

    to_update = []
    for rows in grouped.values():
        previous = None
        for index, row in enumerate(rows):
            row.previous_version_id = previous.id if previous is not None else None
            row.is_current_version = index == len(rows) - 1
            to_update.append(row)
            previous = row
    if to_update:
        ClubPlayer.objects.bulk_update(
            to_update, ["previous_version_id", "is_current_version"]
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_club_player_versioning_simplified"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clubplayer",
            name="unique_club_player_version",
        ),
        migrations.AddField(
            model_name="clubplayer",
            name="is_current_version",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text=(
                    "True iff this is the current club-local identity for "
                    "its (club, player_profile) pair. At most one current "
                    "version is allowed per pair. Historical versions keep "
                    "False forever."
                ),
            ),
        ),
        migrations.AddField(
            model_name="clubplayer",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "The ClubPlayer version this row replaced. NULL on the "
                    "first version for a (club, player_profile) pair."
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="next_versions",
                to="players.clubplayer",
            ),
        ),
        migrations.RunPython(backfill_current_versions, noop_reverse),
        migrations.AlterField(
            model_name="clubplayer",
            name="is_current_version",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text=(
                    "True iff this is the current club-local identity for "
                    "its (club, player_profile) pair. At most one current "
                    "version is allowed per pair. Historical versions keep "
                    "False forever."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="clubplayer",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Club-specific name for this version. Independent from "
                    "PlayerProfile.full_name and never auto-synchronized "
                    "with it."
                ),
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="clubplayer",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text=(
                    "Recency marker for ranking/recommendation, NOT a "
                    "lifecycle flag. Set at creation and bumped when this "
                    "version is resolved again (booking default, explicit "
                    "historical selection, or roster reuse). Never used to "
                    "rewrite an existing Booking."
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clubplayer",
            name="player_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Club-internal jersey or member number for this version.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Player's own preferred personal name. Clubs do not "
                    "overwrite this; club-local naming lives on "
                    "ClubPlayer.display_name and is never auto-synchronized "
                    "with this field."
                ),
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="clubplayer",
            index=models.Index(
                fields=["is_current_version"], name="players_clu_is_curr_5458e9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clubplayer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current_version", True)),
                fields=("club", "player_profile"),
                name="unique_current_club_player_profile",
            ),
        ),
    ]
