# Generated by Django 4.2.15 on 2026-09-13 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0004_club_player_current_version"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="clubplayer",
            name="players_clu_last_us_162286_idx",
        ),
        migrations.RemoveField(
            model_name="clubplayer",
            name="last_used_at",
        ),
        migrations.RemoveField(
            model_name="clubplayer",
            name="updated_at",
        ),
    ]
