# Generated by Django 4.2.15 on 2026-07-26 21:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courts", "0002_recurring_agreements"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "customer_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("start_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CANCELLED", "Cancelled"),
                            ("ACTION_REQUIRED", "Action required"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=32,
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "deposit_status",
                    models.CharField(
                        choices=[
                            ("HELD", "Held"),
                            ("REFUND_DUE", "Refund due"),
                            ("REFUNDED", "Refunded"),
                            ("FORFEITED", "Forfeited"),
                        ],
                        db_index=True,
                        default="HELD",
                        max_length=32,
                    ),
                ),
                (
                    "refund_notice_days_snapshot",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(30)]
                    ),
                ),
                ("deposit_collected_at", models.DateTimeField()),
                (
                    "cancellation_requested_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "cancellation_effective_date",
                    models.DateField(blank=True, null=True),
                ),
                ("cancellation_reason", models.TextField(blank=True)),
                ("refund_due_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("action_required_code", models.CharField(blank=True, max_length=128)),
                (
                    "failed_occurrence_start",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("action_required_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_recurring_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_agreements",
                        to="clubs.club",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_agreements",
                        to="courts.court",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_recurring_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deposit_collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collected_recurring_deposits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "refunded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunded_recurring_deposits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecurringDepositTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("COLLECTION", "Deposit collection"),
                            ("REFUND", "Deposit refund"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("DIGITAL_WALLET", "Digital wallet"),
                            ("BANK_TRANSFER", "Bank transfer"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposit_transactions",
                        to="recurring.recurringagreement",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_deposit_transactions",
                        to="clubs.club",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_deposit_transactions",
                        to="courts.court",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_recurring_deposit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["club", "created"],
                        name="recurring_r_club_id_70aa4d_idx",
                    ),
                    models.Index(
                        fields=["court", "created"],
                        name="recurring_r_court_i_2834ba_idx",
                    ),
                    models.Index(
                        fields=["agreement", "created"],
                        name="recurring_r_agreeme_2eb362_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "created"],
                        name="recurring_r_transac_dcea14_idx",
                    ),
                    models.Index(
                        fields=["created_by", "created"],
                        name="recurring_r_created_a0b2b7_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="recurring_r_referen_5baa60_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="recurringdeposittransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)),
                name="recurring_deposit_transaction_amount_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringdeposittransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference", ""), _negated=True),
                fields=("club", "reference"),
                name="unique_non_blank_recurring_deposit_reference_per_club",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringagreement",
            index=models.Index(
                fields=["club", "status"], name="recurring_r_club_id_61c167_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringagreement",
            index=models.Index(
                fields=["court", "status"], name="recurring_r_court_i_4b6fa9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringagreement",
            index=models.Index(
                fields=["deposit_status"], name="recurring_r_deposit_437c2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringagreement",
            index=models.Index(
                fields=["start_date"], name="recurring_r_start_d_fea9d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringagreement",
            index=models.Index(
                fields=["cancellation_effective_date"],
                name="recurring_r_cancell_1a0082_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringagreement",
            index=models.Index(
                fields=["created"], name="recurring_r_created_7acb3c_idx"
            ),
        ),
    ]
