# Generated by Django 4.2.15 on 2026-08-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recurring", "0001_recurring_agreements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringagreement",
            name="refund_notice_days_snapshot",
        ),
    ]
