# Generated by Django 4.2.15 on 2026-05-18 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("city", models.CharField(db_index=True, max_length=120)),
                ("area", models.CharField(max_length=120)),
                ("address", models.TextField(blank=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("manager_can_settle_transactions", models.BooleanField(default=False)),
                ("manager_can_change_pricing", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_clubs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClubMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("OWNER", "Owner"), ("MANAGER", "Manager")],
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="clubs.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_club_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["club", "role", "is_active"],
                        name="clubs_clubm_club_id_3683cc_idx",
                    ),
                    models.Index(
                        fields=["user", "role", "is_active"],
                        name="clubs_clubm_user_id_b9c560_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="clubmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("club", "user", "role"),
                name="unique_active_club_membership",
            ),
        ),
        migrations.AddConstraint(
            model_name="clubmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("role", "MANAGER")),
                fields=("user", "role"),
                name="unique_active_manager_club_membership",
            ),
        ),
        migrations.AddIndex(
            model_name="club",
            index=models.Index(fields=["name"], name="clubs_club_name_657a0c_idx"),
        ),
        migrations.AddIndex(
            model_name="club",
            index=models.Index(fields=["city"], name="clubs_club_city_d624ea_idx"),
        ),
        migrations.AddIndex(
            model_name="club",
            index=models.Index(
                fields=["is_active"], name="clubs_club_is_acti_ef120d_idx"
            ),
        ),
    ]
