# Generated by Django 4.2.15 on 2026-07-14 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courts", "0001_initial"),
        ("clubs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmembership",
            name="court",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="courts.court",
            ),
        ),
        migrations.AddField(
            model_name="clubmembership",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_club_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clubmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_clubs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="clubmembership",
            index=models.Index(
                fields=["club", "role", "is_active"],
                name="clubs_clubm_club_id_3683cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clubmembership",
            index=models.Index(
                fields=["court", "role", "is_active"],
                name="clubs_clubm_court_i_8cb54c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clubmembership",
            index=models.Index(
                fields=["user", "role", "is_active"],
                name="clubs_clubm_user_id_b9c560_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="clubmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("court__isnull", True),
                    ("is_active", True),
                    ("role__in", ("OWNER", "MANAGER")),
                ),
                fields=("club", "user", "role"),
                name="unique_active_club_role_membership",
            ),
        ),
        migrations.AddConstraint(
            model_name="clubmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("role", "STAFF")),
                fields=("club", "user", "role", "court"),
                name="unique_active_staff_membership",
            ),
        ),
        migrations.AddConstraint(
            model_name="clubmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("role", "MANAGER")),
                fields=("user", "role"),
                name="unique_active_manager_club_membership",
            ),
        ),
        migrations.AddConstraint(
            model_name="clubmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("role", "STAFF")),
                fields=("user", "role"),
                name="unique_active_staff_club_membership",
            ),
        ),
        migrations.AddIndex(
            model_name="club",
            index=models.Index(fields=["name"], name="clubs_club_name_657a0c_idx"),
        ),
        migrations.AddIndex(
            model_name="club",
            index=models.Index(fields=["city"], name="clubs_club_city_d624ea_idx"),
        ),
        migrations.AddIndex(
            model_name="club",
            index=models.Index(
                fields=["is_active"], name="clubs_club_is_acti_ef120d_idx"
            ),
        ),
    ]
