# Generated by Codex on 2026-07-23

from django.db import migrations, models
import django.db.models


def copy_manager_permission_flags(apps, schema_editor):
    ClubMembership = apps.get_model("clubs", "ClubMembership")
    manager_memberships = ClubMembership.objects.filter(role="MANAGER").select_related(
        "club"
    )
    for membership in manager_memberships.iterator():
        membership.manager_can_settle_transactions = (
            membership.club.manager_can_settle_transactions
        )
        membership.manager_can_change_pricing = (
            membership.club.manager_can_change_pricing
        )
        membership.save(
            update_fields=[
                "manager_can_settle_transactions",
                "manager_can_change_pricing",
            ]
        )


def clear_manager_permission_flags(apps, schema_editor):
    ClubMembership = apps.get_model("clubs", "ClubMembership")
    ClubMembership.objects.update(
        manager_can_settle_transactions=False,
        manager_can_change_pricing=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmembership",
            name="manager_can_settle_transactions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clubmembership",
            name="manager_can_change_pricing",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            copy_manager_permission_flags,
            clear_manager_permission_flags,
        ),
        migrations.AddConstraint(
            model_name="clubmembership",
            constraint=models.CheckConstraint(
                check=django.db.models.Q(("role", "MANAGER"))
                | (
                    django.db.models.Q(("manager_can_settle_transactions", False))
                    & django.db.models.Q(("manager_can_change_pricing", False))
                ),
                name="club_membership_manager_flags_only_for_managers",
            ),
        ),
        migrations.RemoveField(
            model_name="club",
            name="manager_can_settle_transactions",
        ),
        migrations.RemoveField(
            model_name="club",
            name="manager_can_change_pricing",
        ),
    ]
