# Generated by Django 4.2.15 on 2026-08-26 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmembership",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="clubmembership",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_club_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="clubmembership",
            index=models.Index(
                fields=["club", "deleted_at"], name="clubs_clubm_club_id_153769_idx"
            ),
        ),
    ]
