# Generated by Django 4.2.15 on 2026-09-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0003_membership_soft_delete_and_membership_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmembership",
            name="last_sync_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
