# Generated by Django 4.2.15 on 2026-09-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0004_membership_last_sync_at"),
        ("profiles", "0002_migrate_membership_identity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClubMembership",
        ),
    ]
