# Generated by Django 4.2.15 on 2026-07-14 14:50

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("courts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("DIGITAL_WALLET", "Digital wallet"),
                            ("BANK_TRANSFER", "Bank transfer"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notes", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="bookings.booking",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="clubs.club",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="courts.court",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["club", "created"],
                        name="transaction_club_id_624681_idx",
                    ),
                    models.Index(
                        fields=["court", "created"],
                        name="transaction_court_i_cb186e_idx",
                    ),
                    models.Index(
                        fields=["booking", "created"],
                        name="transaction_booking_6fe804_idx",
                    ),
                    models.Index(
                        fields=["created_by", "created"],
                        name="transaction_created_544bff_idx",
                    ),
                    models.Index(
                        fields=["payment_method"], name="transaction_payment_77b5ab_idx"
                    ),
                    models.Index(
                        fields=["payment_reference"],
                        name="transaction_payment_ecb923_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)), name="transaction_amount_gt_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("payment_reference", ""), _negated=True),
                fields=("club", "payment_reference"),
                name="unique_non_blank_payment_reference_per_club",
            ),
        ),
    ]
