# Generated by Django 4.2.15 on 2026-08-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transaction",
            name="transaction_amount_gt_zero",
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("PAYMENT", "Payment"), ("REFUND", "Refund")],
                db_index=True,
                default="PAYMENT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["booking", "transaction_type", "is_cancelled"],
                name="transaction_booking_0ae87e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type", "created"],
                name="transaction_transac_be180c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("amount__gt", 0), ("transaction_type", "PAYMENT")),
                    models.Q(("amount__lt", 0), ("transaction_type", "REFUND")),
                    _connector="OR",
                ),
                name="transaction_amount_matches_type",
            ),
        ),
    ]
