# Generated by Django 4.2.15 on 2026-09-08 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_remove_transaction_transaction_amount_gt_zero_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="client_request_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="occurred_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["club", "occurred_at"], name="transaction_club_id_dae85f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_request_id__isnull", False)),
                fields=("club", "client_request_id"),
                name="unique_transaction_client_request_per_club",
            ),
        ),
    ]
