# Generated by Django 4.2.15 on 2026-09-08 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0003_remove_court_recurring_deposit_refund_notice_days_and_more"),
        ("clubs", "0003_membership_soft_delete_and_membership_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0006_booking_attempt_traceability"),
        ("transactions", "0003_transaction_offline_sync_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_request_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("DIGITAL_WALLET", "Digital wallet"),
                            ("BANK_TRANSFER", "Bank transfer"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notes", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("REJECTED", "Rejected")],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=128)),
                ("failure_details", models.JSONField(blank=True, default=dict)),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("UNRESOLVED", "Unresolved"),
                            ("DISMISSED", "Dismissed"),
                            ("RESOLVED", "Resolved"),
                        ],
                        db_index=True,
                        default="UNRESOLVED",
                        max_length=32,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "attempted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_attempts",
                        to="bookings.booking",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_attempts",
                        to="clubs.club",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_attempts",
                        to="courts.court",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["club", "created"],
                        name="transaction_club_id_7541ad_idx",
                    ),
                    models.Index(
                        fields=["club", "outcome", "created"],
                        name="transaction_club_id_66bee0_idx",
                    ),
                    models.Index(
                        fields=["attempted_by", "created"],
                        name="transaction_attempt_5165ad_idx",
                    ),
                    models.Index(
                        fields=["court", "created"],
                        name="transaction_court_i_a5f77e_idx",
                    ),
                    models.Index(
                        fields=["booking", "created"],
                        name="transaction_booking_c581c9_idx",
                    ),
                    models.Index(
                        fields=["club", "occurred_at"],
                        name="transaction_club_id_350e79_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="transactionattempt",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)),
                name="transaction_attempt_amount_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="transactionattempt",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("failure_code", ""),
                        ("outcome", "SUCCESS"),
                        ("transaction__isnull", False),
                    ),
                    models.Q(
                        ("outcome", "REJECTED"),
                        ("transaction__isnull", True),
                        models.Q(("failure_code", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="transaction_attempt_outcome_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="transactionattempt",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("outcome", "SUCCESS"), ("resolution", "DISMISSED"), _negated=True
                ),
                name="transaction_attempt_success_not_dismissed",
            ),
        ),
        migrations.AddConstraint(
            model_name="transactionattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_request_id__isnull", False)),
                fields=("club", "client_request_id"),
                name="transaction_attempt_client_request_once_per_club",
            ),
        ),
    ]
