# Generated by Django 4.2.15 on 2026-07-14 14:50

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courts", "0001_initial"),
        ("clubs", "0002_initial"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("SETTLED", "Settled")],
                        db_index=True,
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("transaction_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "settled_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="clubs.club",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="courts.court",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "settled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settled_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SettlementTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="settlements.settlement",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_line",
                        to="transactions.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="settlementtransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)),
                name="settlement_transaction_amount_gt_zero",
            ),
        ),
        migrations.AddIndex(
            model_name="settlement",
            index=models.Index(
                fields=["club", "created"], name="settlements_club_id_b7e06e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="settlement",
            index=models.Index(
                fields=["club", "status"], name="settlements_club_id_173332_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="settlement",
            index=models.Index(
                fields=["club", "period_start", "period_end"],
                name="settlements_club_id_f0cae1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="settlement",
            index=models.Index(
                fields=["court", "period_start", "period_end"],
                name="settlements_court_i_90c42d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="settlement",
            index=models.Index(
                fields=["settled_at"], name="settlements_settled_d0211a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.CheckConstraint(
                check=models.Q(("period_start__lt", models.F("period_end"))),
                name="settlement_period_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.CheckConstraint(
                check=models.Q(("total_amount__gte", 0)),
                name="settlement_total_amount_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.CheckConstraint(
                check=models.Q(("transaction_count__gte", 0)),
                name="settlement_transaction_count_gte_zero",
            ),
        ),
    ]
