# Generated by Django 4.2.15 on 2026-07-26 21:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recurring", "0001_recurring_agreements"),
        ("settlements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementRecurringDepositTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="settlement",
            name="settlement_total_amount_gte_zero",
        ),
        migrations.AlterField(
            model_name="settlement",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name="settlementrecurringdeposittransaction",
            name="recurring_deposit_transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settlement_deposit_line",
                to="recurring.recurringdeposittransaction",
            ),
        ),
        migrations.AddField(
            model_name="settlementrecurringdeposittransaction",
            name="settlement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deposit_lines",
                to="settlements.settlement",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementrecurringdeposittransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)),
                name="settlement_recurring_deposit_amount_gt_zero",
            ),
        ),
    ]
