# Generated by Django 4.2.15 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="settlement",
            name="settlement_total_amount_gte_zero",
        ),
        migrations.AlterField(
            model_name="settlement",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
