# Generated by Django 4.2.15 on 2026-08-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements", "0002_recurring_agreements"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="settlementtransaction",
            name="settlement_transaction_amount_gt_zero",
        ),
        migrations.AlterField(
            model_name="settlementtransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name="settlementtransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("amount", 0), _negated=True),
                name="settlement_transaction_amount_non_zero",
            ),
        ),
    ]
