# Generated by Django 4.2.15 on 2026-07-14 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("BOOKING_CREATED", "Booking created"),
                            ("BOOKING_UPDATED", "Booking updated"),
                            ("BOOKING_CANCELLED", "Booking cancelled"),
                            ("BOOKING_COMPLETED", "Booking completed"),
                            ("BOOKING_NO_SHOW", "Booking no-show"),
                            ("BOOKING_EXPIRED", "Booking expired"),
                            ("TRANSACTION_CREATED", "Transaction created"),
                            ("SETTLEMENT_CREATED", "Settlement created"),
                            ("SETTLEMENT_MARKED_SETTLED", "Settlement marked settled"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=64)),
                ("entity_id", models.PositiveIntegerField(db_index=True)),
                ("before_data", models.JSONField(blank=True, default=dict)),
                ("after_data", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created", "-id"),
            },
        ),
    ]
