# Generated by Django 4.2.15 on 2026-07-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courts", "0001_initial"),
        ("clubs", "0001_initial"),
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="clubs.club",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="court",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="courts.court",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["club", "created"], name="audit_audit_club_id_8cdbd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["club", "action"], name="audit_audit_club_id_162422_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["club", "entity_type", "entity_id"],
                name="audit_audit_club_id_eeb91b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["club", "actor", "created"],
                name="audit_audit_club_id_4c8dfa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["club", "court", "created"],
                name="audit_audit_club_id_80abe0_idx",
            ),
        ),
    ]
