# Generated by Django 4.2.15 on 2026-08-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_recurring_agreements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("BOOKING_CREATED", "Booking created"),
                    ("BOOKING_UPDATED", "Booking updated"),
                    ("BOOKING_CANCELLED", "Booking cancelled"),
                    ("BOOKING_COMPLETED", "Booking completed"),
                    ("BOOKING_NO_SHOW", "Booking no-show"),
                    ("BOOKING_EXPIRED", "Booking expired"),
                    ("BOOKING_RESCHEDULED", "Booking rescheduled"),
                    ("TRANSACTION_CREATED", "Transaction created"),
                    ("TRANSACTION_CANCELLED", "Transaction cancelled"),
                    ("SETTLEMENT_CREATED", "Settlement created"),
                    ("SETTLEMENT_MARKED_SETTLED", "Settlement marked settled"),
                    ("RECURRING_AGREEMENT_CREATED", "Recurring agreement created"),
                    ("RECURRING_AGREEMENT_CANCELLED", "Recurring agreement cancelled"),
                    (
                        "RECURRING_AGREEMENT_AUTO_TERMINATED",
                        "Recurring agreement automatically terminated",
                    ),
                    ("RECURRING_DEPOSIT_COLLECTED", "Recurring deposit collected"),
                    ("RECURRING_DEPOSIT_REFUND_DUE", "Recurring deposit refund due"),
                    ("RECURRING_DEPOSIT_REFUNDED", "Recurring deposit refunded"),
                    ("RECURRING_DEPOSIT_FORFEITED", "Recurring deposit forfeited"),
                    (
                        "RECURRING_OCCURRENCE_GENERATED",
                        "Recurring occurrence generated",
                    ),
                    ("RECURRING_GENERATION_FAILED", "Recurring generation failed"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
