# Generated by Django 4.2.15 on 2026-07-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("BOOKING_CREATED", "Booking created"),
                    ("BOOKING_UPDATED", "Booking updated"),
                    ("BOOKING_CANCELLED", "Booking cancelled"),
                    ("BOOKING_COMPLETED", "Booking completed"),
                    ("BOOKING_NO_SHOW", "Booking no-show"),
                    ("BOOKING_EXPIRED", "Booking expired"),
                    ("BOOKING_RESCHEDULED", "Booking rescheduled"),
                    ("TRANSACTION_CREATED", "Transaction created"),
                    ("TRANSACTION_CANCELLED", "Transaction cancelled"),
                    ("SETTLEMENT_CREATED", "Settlement created"),
                    ("SETTLEMENT_MARKED_SETTLED", "Settlement marked settled"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
