# Generated by Django 4.2.15 on 2026-08-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="source",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("ADMIN_CORRECTION", "Admin correction"),
                    ("RECURRING", "Recurring"),
                ],
                db_index=True,
                default="MANUAL",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="recurrence_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACTIVE", "Active"),
                    ("RENEWED", "Renewed"),
                    ("ENDED", "Ended"),
                ],
                db_index=True,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="previous_recurring_booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_recurring_booking",
                to="bookings.booking",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["court", "source", "recurrence_status"],
                name="bookings_bo_court_i_d3b92f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("source", "RECURRING"), _negated=True)
                | models.Q(("recurrence_status__isnull", False)),
                name="booking_recurring_source_requires_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("source", "RECURRING"))
                | models.Q(("recurrence_status__isnull", True)),
                name="booking_non_recurring_status_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("source", "RECURRING"))
                | models.Q(("previous_recurring_booking__isnull", True)),
                name="booking_non_recurring_previous_null",
            ),
        ),
    ]
