# Generated by Django 4.2.15 on 2026-07-26 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recurring", "0001_recurring_agreements"),
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="recurring_agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="recurring.recurringagreement",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="source",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("ADMIN_CORRECTION", "Admin correction"),
                    ("RECURRING", "Recurring"),
                ],
                db_index=True,
                default="MANUAL",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["recurring_agreement", "start_time"],
                name="bookings_bo_recurri_cb46fc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recurring_agreement__isnull", False)),
                fields=("recurring_agreement", "start_time"),
                name="unique_recurring_agreement_occurrence_start",
            ),
        ),
    ]
