# Generated by Django 4.2.15 on 2026-09-07 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0003_remove_court_recurring_deposit_refund_notice_days_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0003_membership_soft_delete_and_membership_deleted"),
        ("bookings", "0004_booking_client_request_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_request_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "customer_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("requested_start", models.DateTimeField()),
                ("requested_end", models.DateTimeField()),
                ("requested_at", models.DateTimeField(db_index=True)),
                ("requested_recurring", models.BooleanField(default=False)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("REJECTED", "Rejected")],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=128)),
                ("failure_details", models.JSONField(blank=True, default=dict)),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("UNRESOLVED", "Unresolved"),
                            ("DISMISSED", "Dismissed"),
                            ("RESOLVED", "Resolved"),
                        ],
                        db_index=True,
                        default="UNRESOLVED",
                        max_length=32,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "attempted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to="bookings.booking",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_attempts",
                        to="clubs.club",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_attempts",
                        to="courts.court",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["club", "created"],
                        name="bookings_bo_club_id_81e3a7_idx",
                    ),
                    models.Index(
                        fields=["club", "outcome", "created"],
                        name="bookings_bo_club_id_c14150_idx",
                    ),
                    models.Index(
                        fields=["attempted_by", "created"],
                        name="bookings_bo_attempt_30d1f4_idx",
                    ),
                    models.Index(
                        fields=["court", "created"],
                        name="bookings_bo_court_i_d514e5_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="bookingattempt",
            constraint=models.CheckConstraint(
                check=models.Q(("requested_start__lt", models.F("requested_end"))),
                name="booking_attempt_requested_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingattempt",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("booking__isnull", False),
                        ("failure_code", ""),
                        ("outcome", "SUCCESS"),
                    ),
                    models.Q(
                        ("booking__isnull", True),
                        ("outcome", "REJECTED"),
                        models.Q(("failure_code", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="booking_attempt_outcome_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_request_id__isnull", False)),
                fields=("club", "client_request_id"),
                name="booking_attempt_client_request_once_per_club",
            ),
        ),
    ]
