# Generated by Django 4.2.15 on 2026-09-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_bookingattempt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingattempt",
            name="requested_source",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("ADMIN_CORRECTION", "Admin correction"),
                    ("RECURRING", "Recurring"),
                ],
                db_index=True,
                default="MANUAL",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="bookingattempt",
            index=models.Index(
                fields=["club", "requested_start"],
                name="bookings_bo_club_id_dcf2ae_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingattempt",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("requested_recurring", True), ("requested_source", "RECURRING")
                    ),
                    models.Q(
                        models.Q(("requested_source", "RECURRING"), _negated=True),
                        ("requested_recurring", False),
                    ),
                    _connector="OR",
                ),
                name="booking_attempt_source_matches_recurring_intent",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingattempt",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("outcome", "SUCCESS"), ("resolution", "DISMISSED"), _negated=True
                ),
                name="booking_attempt_success_not_dismissed",
            ),
        ),
    ]
