# Generated by Django 4.2.15 on 2026-09-10 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0006_booking_attempt_traceability'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_status_changed_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_status_changed_by_type',
            field=models.CharField(blank=True, choices=[('INTERNAL_USER', 'Internal user'), ('SYSTEM', 'System')], max_length=32, null=True),
        ),
    ]
