# Generated by Django 4.2.15 on 2026-09-13 17:56

import django.db.models.deletion
from django.db import migrations, models


def add_club_player_club_composite_fk(apps, schema_editor):
    """
    PostgreSQL-only: enforce Booking.club_id == Booking.club_player.club_id
    at the database level using a composite foreign key.

    ClubPlayer.id is already a primary key (and therefore already unique on
    its own), but Postgres requires a unique constraint matching the exact
    column tuple referenced by a composite foreign key. Adding
    UNIQUE(id, club_id) lets us define:

        Booking(club_player_id, club_id) REFERENCES ClubPlayer(id, club_id)

    which makes it structurally impossible to store a Booking row whose
    club_player belongs to a different club than the booking itself
    (Postgres FK "MATCH SIMPLE" semantics allow club_player_id to be NULL
    without triggering the check, which matches the nullable column).

    SQLite (used for local dev/tests via DB_ENGINE=sqlite) does not support
    adding foreign key constraints to an existing table without a full
    table rebuild, so this is a no-op there. The invariant is still
    enforced on every backend at the application layer by Booking.clean()
    and apps.bookings.services.validate_booking_club_player().
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "ALTER TABLE players_clubplayer "
        "ADD CONSTRAINT unique_clubplayer_id_club UNIQUE (id, club_id);"
    )
    schema_editor.execute(
        "ALTER TABLE bookings_booking "
        "ADD CONSTRAINT booking_club_player_club_match "
        "FOREIGN KEY (club_player_id, club_id) "
        "REFERENCES players_clubplayer (id, club_id);"
    )


def remove_club_player_club_composite_fk(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "ALTER TABLE bookings_booking "
        "DROP CONSTRAINT booking_club_player_club_match;"
    )
    schema_editor.execute(
        "ALTER TABLE players_clubplayer DROP CONSTRAINT unique_clubplayer_id_club;"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
        ("bookings", "0007_booking_last_status_changed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="club_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="players.clubplayer",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["club_player"], name="bookings_bo_club_pl_81fe63_idx"
            ),
        ),
        migrations.RunPython(
            add_club_player_club_composite_fk,
            remove_club_player_club_composite_fk,
        ),
    ]
