# Generated by Django 4.2.15 on 2026-07-14 14:50

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sport_type",
                    models.CharField(
                        choices=[("FOOTBALL", "Football")],
                        db_index=True,
                        default="FOOTBALL",
                        max_length=32,
                    ),
                ),
                (
                    "default_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "slot_duration_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "requires_digital_payment_reference",
                    models.BooleanField(default=False),
                ),
                (
                    "internal_hold_expiry_hours",
                    models.PositiveIntegerField(
                        default=12,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courts",
                        to="clubs.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_courts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourtWorkingHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("opens_at", models.TimeField(blank=True, null=True)),
                ("closes_at", models.TimeField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="courts.court",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["court", "weekday"],
                        name="courts_cour_court_i_3106cc_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="courtworkinghour",
            constraint=models.UniqueConstraint(
                fields=("court", "weekday"), name="unique_court_weekday_working_hour"
            ),
        ),
        migrations.AddIndex(
            model_name="court",
            index=models.Index(fields=["club"], name="courts_cour_club_id_3e6012_idx"),
        ),
        migrations.AddIndex(
            model_name="court",
            index=models.Index(
                fields=["is_active"], name="courts_cour_is_acti_bc541b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="court",
            index=models.Index(
                fields=["sport_type"], name="courts_cour_sport_t_082085_idx"
            ),
        ),
    ]
