# Generated by Django 4.2.15 on 2026-07-14 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="players_count",
            field=models.IntegerField(default=10, max_length=100),
        ),
        migrations.AlterField(
            model_name="court",
            name="internal_hold_expiry_hours",
            field=models.PositiveIntegerField(
                default=12,
                help_text="OnHold period without payment",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="court",
            name="sport_type",
            field=models.CharField(
                choices=[
                    ("FOOTBALL", "Football"),
                    ("PADEL", "Padel"),
                    ("TENNIS", "Tennis"),
                ],
                db_index=True,
                default="FOOTBALL",
                max_length=32,
            ),
        ),
    ]
