# Generated by Django 4.2.15 on 2026-08-24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="cancellation_refund_notice_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Null means the cancellation refund policy is not configured. 0 means refundable until the affected occurrence starts. 1-30 is the required calendar-day notice.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(30)],
            ),
        ),
    ]
