# Generated by Django 4.2.15 on 2026-08-16 12:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0002_recurring_agreements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="cancellation_refund_notice_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Null means the cancellation refund policy is not configured. 0 means refundable until the affected occurrence starts. 1-30 is the required calendar-day notice.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(30)],
            ),
        ),
        migrations.AddField(
            model_name="court",
            name="minimum_deposit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.RemoveField(
            model_name="courtworkinghour",
            name="closes_at",
        ),
        migrations.RemoveField(
            model_name="courtworkinghour",
            name="is_closed",
        ),
        migrations.RemoveField(
            model_name="courtworkinghour",
            name="opens_at",
        ),
    ]
