# Generated by Django 4.2.15 on 2026-07-14 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0002_court_players_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="players_count",
            field=models.PositiveIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
