# Generated by Codex on 2026-07-22

from decimal import Decimal

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0003_alter_court_players_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourtWorkingHourPricePeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "working_hour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_periods",
                        to="courts.courtworkinghour",
                    ),
                ),
            ],
            options={
                "ordering": ("starts_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["working_hour", "starts_at"],
                        name="courts_cour_working_f17ca5_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="courtworkinghourpriceperiod",
            constraint=models.CheckConstraint(
                check=models.Q(("starts_at__lt", models.F("ends_at"))),
                name="court_price_period_starts_before_ends",
            ),
        ),
        migrations.AddConstraint(
            model_name="courtworkinghourpriceperiod",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", Decimal("0.00"))),
                name="court_price_period_price_non_negative",
            ),
        ),
    ]
