# Generated by Django 4.2.15 on 2026-09-10 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_remove_court_recurring_deposit_refund_notice_days_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courtworkinghourpriceperiod',
            name='court_price_period_starts_before_ends',
        ),
        migrations.AddConstraint(
            model_name='courtworkinghourpriceperiod',
            constraint=models.CheckConstraint(check=models.Q(('starts_at__lt', models.F('ends_at')), models.Q(('ends_at', datetime.time(0, 0)), models.Q(('starts_at', datetime.time(0, 0)), _negated=True)), _connector='OR'), name='court_price_period_starts_before_ends'),
        ),
    ]
