# Generated by Codex on 2026-07-22

from django.db import migrations


def backfill_price_periods(apps, schema_editor):
    CourtWorkingHour = apps.get_model("courts", "CourtWorkingHour")
    CourtWorkingHourPricePeriod = apps.get_model(
        "courts",
        "CourtWorkingHourPricePeriod",
    )

    existing_working_hour_ids = set(
        CourtWorkingHourPricePeriod.objects.values_list("working_hour_id", flat=True)
    )
    periods = []
    working_hours = (
        CourtWorkingHour.objects.filter(
            is_closed=False,
            opens_at__isnull=False,
            closes_at__isnull=False,
        )
        .select_related("court")
        .order_by("id")
    )
    for working_hour in working_hours:
        if working_hour.id in existing_working_hour_ids:
            continue
        periods.append(
            CourtWorkingHourPricePeriod(
                working_hour_id=working_hour.id,
                starts_at=working_hour.opens_at,
                ends_at=working_hour.closes_at,
                price=working_hour.court.default_price,
            )
        )
    CourtWorkingHourPricePeriod.objects.bulk_create(periods, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0004_courtworkinghourpriceperiod"),
    ]

    operations = [
        migrations.RunPython(backfill_price_periods, migrations.RunPython.noop),
    ]
